// <auto-generated />
namespace WebShopThoiTrang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Table_ReviewEdit_ForenKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Table_ReviewEdit_ForenKey));
        
        string IMigrationMetadata.Id
        {
            get { return "202311201339387_Table_Review-Edit_ForenKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
